#######################################################################
#  ████████▄     ▄████████    ▄████████    ▄████████    ▄█   ▄█▄      #
#  ███   ▀███   ███    ███   ███    ███   ███    ███   ███ ▄███▀      #
#  ███    ███   ███    ███   ███    █▀    ███    ███   ███▐██▀        #
#  ███    ███   ███    ███  ▄███▄▄▄      ▄███▄▄▄▄██▀  ▄█████▀         #
#  ███    ███ ▀███████████ ▀▀███▀▀▀       ███▀▀▀▀▀   ▀▀█████▄         #
#  ███    ███   ███    ███   ███    █▄   ▀██████████   ███▐██▄        #
#  ███   ▄███   ███    ███   ███    ███   ███    ███   ███ ▀███▄      #
#  ████████▀    ███    █▀    ██████████   ███    ███   ███   ▀█▀      #
#                                                                     #
#######################################################################


config:
  prefix: "&7[&a&lK&f&lB&7]"

  welcome_message:
    enable: true
    message:
    - '&a&m                        '
    - '&e¡Bienvenido &a%player%&e!'
    - ''
    - '&e Mensaje del día: &aMiau'
    - '&a&m                        '

  teleport_on_join:
    enable: false
    Location:
    - 'world'      # Mundo
    - '268.5'      # Coordenada X
    - '-24.5'      # Coordenada Y
    - '119'        # Coordenada Z
    - '90'         # Yaw
    - '0'          # Pitch

  block_break_rewards:
    enabled: true
    blocks:
      COAL_ORE:
        chance: 25 # 25%
        multiplier: 1.0
      DEEPSLATE_COAL_ORE:
        chance: 25 # 25%
        multiplier: 1.0  
      IRON_ORE:
        chance: 20 # 20%
        multiplier: 1.0
      DEEPSLATE_IRON_ORE:
        chance: 20 # 20%
        multiplier: 1.0
      GOLD_ORE:
        chance: 15 # 15%
        multiplier: 1.0
      DEEPSLATE_GOLD_ORE:
        chance: 15 # 15%
        multiplier: 1.0
      DIAMOND_ORE:
        chance: 10 # 10%
        multiplier: 1.0
      DEEPSLATE_DIAMOND_ORE:
        chance: 10 # 10%
        multiplier: 1.0
      EMERALD_ORE:
        chance: 5 # 5%
        multiplier: 1.0
      DEEPSLATE_EMERALD_ORE:
        chance: 5 # 5%
        multiplier: 1.0
      LAPIS_ORE:
        chance: 10 # 10%
        multiplier: 1.0
      DEEPSLATE_LAPIS_ORE:
        chance: 10 # 10%
        multiplier: 1.0
      NETHER_QUARTZ_ORE:
        chance: 20 # 20%
        multiplier: 1.0
      ANCIENT_DEBRIS:
        chance: 20 # 20%
        multiplier: 1.0

messages:
  prevent_block_break: " &c¡No puedes romper bloques aquí!"

  block_words_message: " &c¡No puedes escribir eso aquí!"